-- Run this AFTER the initial schema migration. Seeds industries from src/data/industries.ts

INSERT INTO public.industries (id, name, icon, description, min_budget, monthly_cost_per_person) VALUES
('clothing', 'Clothing & Fashion', '👗', 'Start your own clothing brand or boutique', 5000, 800),
('food', 'Food & Restaurant', '🍕', 'Launch a food business, restaurant, or catering service', 8000, 1200),
('youtube', 'YouTube / Content Creation', '🎬', 'Start a YouTube channel or content creation business', 2000, 500),
('cosmetics', 'Cosmetics & Beauty', '💄', 'Launch your own beauty or skincare brand', 6000, 1000),
('tech', 'Tech / SaaS', '💻', 'Build a tech startup or SaaS product', 10000, 2000)
ON CONFLICT (id) DO NOTHING;

-- industry_expenses
INSERT INTO public.industry_expenses (industry_id, category, amount, description, is_monthly) VALUES
('clothing', 'Inventory & Materials', 2000, 'Initial fabric and clothing stock', false),
('clothing', 'Branding & Design', 800, 'Logo, packaging, labels', false),
('clothing', 'E-commerce Setup', 500, 'Website, domain, hosting', false),
('clothing', 'Marketing', 1000, 'Social media ads, influencer outreach', true),
('clothing', 'Equipment', 400, 'Sewing machine, tools', false),
('clothing', 'Legal & Permits', 300, 'Business registration, permits', false),
('clothing', 'Team Salary', 1500, 'Monthly salary per team member', true),
('food', 'Kitchen Equipment', 3000, 'Ovens, refrigerators, utensils', false),
('food', 'Initial Ingredients', 1500, 'First month''s raw materials', false),
('food', 'Rent & Utilities', 1500, 'Kitchen space or food truck lease', true),
('food', 'Licensing', 800, 'Food safety permits, business license', false),
('food', 'Marketing', 700, 'Menu design, local advertising', true),
('food', 'Packaging', 500, 'Containers, bags, branding', false),
('food', 'Team Salary', 1800, 'Monthly salary per team member', true),
('youtube', 'Camera Equipment', 800, 'Camera, lenses, tripod', false),
('youtube', 'Audio Equipment', 300, 'Microphone, audio interface', false),
('youtube', 'Lighting', 200, 'Ring light, softbox setup', false),
('youtube', 'Editing Software', 200, 'Premiere Pro, After Effects subscription', true),
('youtube', 'Studio Setup', 300, 'Backdrop, desk, decor', false),
('youtube', 'Initial Promotion', 200, 'Social media ads to boost first videos', true),
('cosmetics', 'Product Development', 2000, 'Formulation, testing, samples', false),
('cosmetics', 'Packaging & Labels', 1200, 'Bottles, jars, custom labels', false),
('cosmetics', 'Certifications', 800, 'FDA compliance, safety testing', false),
('cosmetics', 'E-commerce', 500, 'Website and payment gateway', false),
('cosmetics', 'Marketing', 1000, 'Influencer partnerships, ads', true),
('cosmetics', 'Initial Inventory', 500, 'First batch production', false),
('cosmetics', 'Team Salary', 1200, 'Monthly salary per team member', true),
('tech', 'Development', 4000, 'MVP development, freelancers', false),
('tech', 'Cloud & Hosting', 1200, 'AWS/GCP, domain, SSL', true),
('tech', 'Design & UX', 1500, 'UI/UX design, prototyping', false),
('tech', 'Legal', 1000, 'Incorporation, terms of service', false),
('tech', 'Marketing', 1500, 'Landing page, PPC, content', true),
('tech', 'Tools & Licenses', 800, 'Software subscriptions', true),
('tech', 'Team Salary', 3000, 'Monthly salary per team member', true);

-- industry_influencers
INSERT INTO public.industry_influencers (industry_id, name, platform, followers, charge, specialty) VALUES
('clothing', 'Fashion Nova Girl', 'Instagram', '500K', 2000, 'Streetwear & Casual'),
('clothing', 'Style Maven', 'TikTok', '1.2M', 3500, 'Luxury Fashion'),
('clothing', 'Outfit Daily', 'YouTube', '800K', 2500, 'Budget Fashion'),
('food', 'FoodieExplorer', 'Instagram', '300K', 1500, 'Restaurant Reviews'),
('food', 'Chef''s Table', 'YouTube', '2M', 5000, 'Cooking Tutorials'),
('food', 'TasteBud Travels', 'TikTok', '900K', 2000, 'Street Food'),
('youtube', 'Creator Academy', 'YouTube', '1.5M', 500, 'Creator Tips'),
('youtube', 'TechReviewPro', 'YouTube', '3M', 8000, 'Tech Reviews'),
('youtube', 'VlogLife', 'Instagram', '600K', 1200, 'Lifestyle Vlogs'),
('cosmetics', 'GlowUp Queen', 'Instagram', '700K', 2500, 'Skincare Routines'),
('cosmetics', 'MakeupByMia', 'TikTok', '1.8M', 4000, 'Makeup Tutorials'),
('cosmetics', 'Beauty Insider', 'YouTube', '1.1M', 3000, 'Product Reviews'),
('tech', 'TechCrunch Writer', 'Twitter', '200K', 3000, 'Startup Coverage'),
('tech', 'SaaS Weekly', 'Newsletter', '50K', 1000, 'SaaS Reviews'),
('tech', 'DevTok', 'TikTok', '400K', 1500, 'Tech Tutorials');

-- industry_materials
INSERT INTO public.industry_materials (industry_id, name, supplier, estimated_cost, unit, notes) VALUES
('clothing', 'Cotton Fabric', 'FabricMart', 8, 'per yard', 'Bulk discounts available'),
('clothing', 'Polyester Blend', 'TextilePro', 5, 'per yard', 'Quick-dry material'),
('clothing', 'Labels & Tags', 'LabelKing', 0.15, 'per piece', 'Custom branding'),
('clothing', 'Packaging Boxes', 'PackRight', 1.5, 'per box', 'Eco-friendly options'),
('food', 'Commercial Oven', 'KitchenPro', 1200, 'per unit', 'Energy efficient'),
('food', 'Bulk Ingredients', 'WholeFoods Supply', 500, 'monthly', 'Organic options'),
('food', 'Food Containers', 'EcoPack', 0.3, 'per piece', 'Biodegradable'),
('food', 'Uniforms', 'ChefWear', 35, 'per set', 'Custom embroidery'),
('youtube', 'DSLR Camera', 'CameraWorld', 600, 'per unit', '4K capable'),
('youtube', 'Wireless Mic', 'AudioTech', 150, 'per set', 'Lavalier type'),
('youtube', 'LED Panel Light', 'LightPro', 80, 'per unit', 'Adjustable temp'),
('youtube', 'Green Screen', 'StudioGear', 40, 'per unit', 'Collapsible'),
('cosmetics', 'Base Oils', 'NaturalEssence', 25, 'per liter', 'Organic certified'),
('cosmetics', 'Glass Jars 50ml', 'PackBeauty', 1.2, 'per piece', 'Frosted finish'),
('cosmetics', 'Pigment Powders', 'ColorTech', 15, 'per 100g', 'Cosmetic grade'),
('cosmetics', 'Safety Seals', 'SecurePack', 0.1, 'per piece', 'Tamper-evident'),
('tech', 'Cloud Credits', 'AWS/GCP', 100, 'monthly', 'Startup programs available'),
('tech', 'Domain Name', 'Namecheap', 12, 'yearly', '.com preferred'),
('tech', 'Design Tools', 'Figma', 15, 'monthly', 'Per editor seat'),
('tech', 'Analytics', 'Mixpanel', 0, 'monthly', 'Free tier available');

-- industry_roadmap
INSERT INTO public.industry_roadmap (industry_id, step, title, description, duration, cost) VALUES
('clothing', 1, 'Market Research', 'Identify target audience, analyze competitors, and find your niche', '2 weeks', 0),
('clothing', 2, 'Brand Identity', 'Create logo, brand colors, and overall aesthetic', '1 week', 800),
('clothing', 3, 'Source Materials', 'Find reliable fabric suppliers and negotiate prices', '2 weeks', 2000),
('clothing', 4, 'Create First Collection', 'Design and produce your initial product line', '4 weeks', 500),
('clothing', 5, 'Launch Online Store', 'Set up e-commerce, product photography, and launch', '2 weeks', 500),
('clothing', 6, 'Marketing Campaign', 'Social media marketing and influencer partnerships', 'Ongoing', 1000),
('food', 1, 'Concept Development', 'Define cuisine type, menu, and unique selling proposition', '2 weeks', 0),
('food', 2, 'Location & Permits', 'Secure kitchen space and obtain required licenses', '4 weeks', 2300),
('food', 3, 'Equipment Setup', 'Purchase and install kitchen equipment', '2 weeks', 3000),
('food', 4, 'Menu Testing', 'Recipe development and taste testing', '2 weeks', 500),
('food', 5, 'Soft Launch', 'Open for limited service to gather feedback', '2 weeks', 1500),
('food', 6, 'Grand Opening', 'Full launch with marketing push', '1 week', 700),
('youtube', 1, 'Niche Selection', 'Choose your content niche and target audience', '1 week', 0),
('youtube', 2, 'Equipment Purchase', 'Get camera, mic, and lighting setup', '1 week', 1300),
('youtube', 3, 'Channel Branding', 'Create logo, banner, intro/outro templates', '1 week', 100),
('youtube', 4, 'Content Planning', 'Plan first 10 videos with scripts and schedules', '1 week', 0),
('youtube', 5, 'First Upload', 'Film, edit, and upload your first video', '1 week', 200),
('youtube', 6, 'Growth Strategy', 'SEO optimization, collaboration, and consistency', 'Ongoing', 200),
('cosmetics', 1, 'Product Research', 'Study market trends and identify product gaps', '2 weeks', 0),
('cosmetics', 2, 'Formulation', 'Develop product formulas with a cosmetic chemist', '4 weeks', 2000),
('cosmetics', 3, 'Safety Testing', 'Get products tested and certified', '3 weeks', 800),
('cosmetics', 4, 'Packaging Design', 'Design and order custom packaging', '3 weeks', 1200),
('cosmetics', 5, 'Online Store Launch', 'Build website and list products', '2 weeks', 500),
('cosmetics', 6, 'Marketing Blitz', 'Influencer seeding and social media campaigns', 'Ongoing', 1000),
('tech', 1, 'Idea Validation', 'Survey potential users and validate the problem', '2 weeks', 0),
('tech', 2, 'MVP Planning', 'Define core features and create wireframes', '2 weeks', 1500),
('tech', 3, 'Development', 'Build the minimum viable product', '8 weeks', 4000),
('tech', 4, 'Beta Testing', 'Launch to early users and gather feedback', '3 weeks', 200),
('tech', 5, 'Launch', 'Public launch with marketing campaign', '2 weeks', 2500),
('tech', 6, 'Iterate & Scale', 'Improve based on feedback, acquire users', 'Ongoing', 1800);

-- industry_resources
INSERT INTO public.industry_resources (industry_id, name, type, monthly_cost, one_time_cost, description, essential) VALUES
('clothing', 'Industrial Sewing Machine', 'equipment', 0, 350, 'Heavy-duty for production', true),
('clothing', 'Shopify Store', 'software', 39, 0, 'E-commerce platform', true),
('clothing', 'Fashion Designer', 'personnel', 2000, 0, 'Freelance or part-time designer', false),
('clothing', 'Photography Studio Rental', 'service', 200, 0, 'Product photoshoots', true),
('clothing', 'Heat Press Machine', 'equipment', 0, 250, 'For custom prints', false),
('food', 'Commercial Kitchen Space', 'service', 1200, 0, 'Shared or private kitchen rental', true),
('food', 'POS System', 'software', 60, 200, 'Point of sale + inventory', true),
('food', 'Delivery Platform Fee', 'service', 150, 0, 'UberEats, DoorDash listing', false),
('food', 'Food Safety Certification', 'service', 0, 300, 'Required by law', true),
('food', 'Line Cook', 'personnel', 2500, 0, 'Full-time kitchen staff', true),
('youtube', 'Adobe Creative Suite', 'software', 55, 0, 'Premiere Pro, Photoshop, etc.', true),
('youtube', 'Video Editor (Freelance)', 'personnel', 500, 0, 'Part-time editing help', false),
('youtube', 'Thumbnail Designer', 'service', 100, 0, 'Per video thumbnail', false),
('youtube', 'Studio Soundproofing', 'equipment', 0, 200, 'Foam panels', true),
('youtube', 'Stock Music License', 'software', 15, 0, 'Royalty-free music', true),
('cosmetics', 'Cosmetic Chemist Consultation', 'service', 0, 1500, 'Formula development', true),
('cosmetics', 'Lab Testing Services', 'service', 0, 800, 'Safety & compliance', true),
('cosmetics', 'Shopify + Beauty Theme', 'software', 39, 80, 'Optimized storefront', true),
('cosmetics', 'Fulfillment Service', 'service', 200, 0, 'Order packing & shipping', false),
('cosmetics', 'Brand Photographer', 'personnel', 300, 0, 'Product photography', true),
('tech', 'Full-Stack Developer', 'personnel', 4000, 0, 'Core product development', true),
('tech', 'AWS/GCP Infrastructure', 'software', 100, 0, 'Cloud hosting & services', true),
('tech', 'CI/CD Pipeline', 'software', 0, 0, 'GitHub Actions (free tier)', true),
('tech', 'UX Designer (Contract)', 'personnel', 1500, 0, 'Part-time design work', false),
('tech', 'Legal Consultation', 'service', 0, 1000, 'Incorporation & ToS', true);
